project_id = "nibnxnfxsypmaijmgcgk"

[functions.leko-chat]
verify_jwt = false

[functions.approve-application]
verify_jwt = false

[functions.activate-pod]
verify_jwt = false

[functions.sign-document]
verify_jwt = false
